import type { Lead, Profile, DailyAttendance, ConfigOccupation } from '@/types/database'

export function isPreviewMode(): boolean {
  return (process.env.NEXT_PUBLIC_SUPABASE_URL ?? '').includes('placeholder')
}

export const MOCK_USER = {
  id: 'mock-user-id',
  email: 'agent@qualex.com',
}

export const MOCK_PROFILE: Profile = {
  id: 'mock-user-id',
  full_name: 'Ahmed Hassan',
  role: 'telesales_agent',
  team: 'telesales',
  is_active: true,
  is_on_break: false,
  break_started_at: null,
  shift_start: '09:00',
  shift_end: '18:00',
}

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-001',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    name: 'Mohamed Salah',
    phone: '+201012345678',
    phone_normalized: '+201012345678',
    channel: 'whatsapp',
    requested_car_brand: 'Toyota',
    requested_car_year: 2023,
    source_campaign: 'ramadan_promo',
    is_duplicate: false,
    duplicate_of: null,
    channel_history: [],
    assigned_telesales_agent: 'mock-user-id',
    assigned_direct_sales_agent: null,
    telesales_assigned_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    telesales_qualified_at: null,
    direct_sales_assigned_at: null,
    stage: 'telesales_assigned',
    customer_national_id: null,
    salary_bracket: null,
    down_payment_bracket: null,
    financing_program: null,
    car_source: null,
    knows_specific_car: null,
    occupation: null,
    customer_id_reference: null,
    tele_disposition: null,
    ds_disposition: null,
    tele_sla_due_at: new Date(Date.now() + 25 * 60 * 1000).toISOString(),
    tele_sla_breached: false,
    ds_sla_due_at: null,
    ds_sla_breached: false,
    tele_follow_up_at: null,
    ds_follow_up_at: null,
    id_document_url: null,
    tele_notes: null,
    ds_notes: null,
    unqualification_reason: null,
  },
  {
    id: 'lead-002',
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    name: 'Nour Khalil',
    phone: '+201123456789',
    phone_normalized: '+201123456789',
    channel: 'meta',
    requested_car_brand: 'Hyundai',
    requested_car_year: 2024,
    source_campaign: 'facebook_summer',
    is_duplicate: false,
    duplicate_of: null,
    channel_history: [],
    assigned_telesales_agent: 'mock-user-id',
    assigned_direct_sales_agent: null,
    telesales_assigned_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    telesales_qualified_at: null,
    direct_sales_assigned_at: null,
    stage: 'telesales_in_progress',
    customer_national_id: null,
    salary_bracket: '10k-15k',
    down_payment_bracket: '50k-100k',
    financing_program: null,
    car_source: null,
    knows_specific_car: false,
    occupation: null,
    customer_id_reference: null,
    tele_disposition: null,
    ds_disposition: null,
    tele_sla_due_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    tele_sla_breached: true,
    ds_sla_due_at: null,
    ds_sla_breached: false,
    tele_follow_up_at: null,
    ds_follow_up_at: null,
    id_document_url: null,
    tele_notes: 'Customer interested in Elantra, asked about monthly installments.',
    ds_notes: null,
    unqualification_reason: null,
  },
  {
    id: 'lead-003',
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    name: 'Amira Mostafa',
    phone: '+201234567890',
    phone_normalized: '+201234567890',
    channel: 'website',
    requested_car_brand: 'Kia',
    requested_car_year: 2023,
    source_campaign: null,
    is_duplicate: false,
    duplicate_of: null,
    channel_history: [],
    assigned_telesales_agent: 'mock-user-id',
    assigned_direct_sales_agent: 'ds-agent-001',
    telesales_assigned_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    telesales_qualified_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    direct_sales_assigned_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    stage: 'qualified',
    customer_national_id: null,
    salary_bracket: '15k-20k',
    down_payment_bracket: '100k-150k',
    financing_program: 'new_car',
    car_source: 'dealer',
    knows_specific_car: true,
    occupation: 'engineer',
    customer_id_reference: null,
    tele_disposition: 'qualified',
    ds_disposition: null,
    tele_sla_due_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    tele_sla_breached: false,
    ds_sla_due_at: new Date(Date.now() + 25 * 60 * 1000).toISOString(),
    ds_sla_breached: false,
    tele_follow_up_at: null,
    ds_follow_up_at: null,
    id_document_url: null,
    tele_notes: 'Very interested, knows the exact model she wants.',
    ds_notes: null,
    unqualification_reason: null,
  },
  {
    id: 'lead-004',
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    name: 'Khaled Ibrahim',
    phone: '+201098765432',
    phone_normalized: '+201098765432',
    channel: 'call_center',
    requested_car_brand: 'Toyota',
    requested_car_year: 2022,
    source_campaign: 'outbound_q2',
    is_duplicate: false,
    duplicate_of: null,
    channel_history: [],
    assigned_telesales_agent: 'mock-user-id',
    assigned_direct_sales_agent: null,
    telesales_assigned_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    telesales_qualified_at: null,
    direct_sales_assigned_at: null,
    stage: 'telesales_assigned',
    customer_national_id: null,
    salary_bracket: null,
    down_payment_bracket: null,
    financing_program: null,
    car_source: null,
    knows_specific_car: null,
    occupation: null,
    customer_id_reference: null,
    tele_disposition: null,
    ds_disposition: null,
    tele_sla_due_at: new Date(Date.now() + 25 * 60 * 1000).toISOString(),
    tele_sla_breached: false,
    ds_sla_due_at: null,
    ds_sla_breached: false,
    tele_follow_up_at: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    ds_follow_up_at: null,
    id_document_url: null,
    tele_notes: null,
    ds_notes: null,
    unqualification_reason: null,
  },
  {
    id: 'lead-005',
    created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    name: 'Sara Ahmed',
    phone: '+201555123456',
    phone_normalized: '+201555123456',
    channel: 'meta',
    requested_car_brand: 'Hyundai',
    requested_car_year: 2024,
    source_campaign: 'instagram_reels',
    is_duplicate: false,
    duplicate_of: null,
    channel_history: [
      { channel: 'whatsapp', captured_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(), source: 'whatsapp_bot' },
    ],
    assigned_telesales_agent: 'mock-user-id',
    assigned_direct_sales_agent: 'ds-agent-001',
    telesales_assigned_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    telesales_qualified_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    direct_sales_assigned_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    stage: 'ds_assigned',
    customer_national_id: null,
    salary_bracket: '20k-30k',
    down_payment_bracket: '150k-200k',
    financing_program: 'new_car',
    car_source: 'dealer',
    knows_specific_car: false,
    occupation: 'doctor',
    customer_id_reference: null,
    tele_disposition: 'qualified',
    ds_disposition: null,
    tele_sla_due_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    tele_sla_breached: false,
    ds_sla_due_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    ds_sla_breached: true,
    tele_follow_up_at: null,
    ds_follow_up_at: null,
    id_document_url: null,
    tele_notes: 'Prefers Accent or Elantra. Available afternoons.',
    ds_notes: null,
    unqualification_reason: null,
  },
  {
    id: 'lead-006',
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    name: 'Omar Farouk',
    phone: '+201777654321',
    phone_normalized: '+201777654321',
    channel: 'whatsapp',
    requested_car_brand: 'Kia',
    requested_car_year: 2023,
    source_campaign: null,
    is_duplicate: true,
    duplicate_of: 'lead-001',
    channel_history: [],
    assigned_telesales_agent: null,
    assigned_direct_sales_agent: null,
    telesales_assigned_at: null,
    telesales_qualified_at: null,
    direct_sales_assigned_at: null,
    stage: 'new',
    customer_national_id: null,
    salary_bracket: null,
    down_payment_bracket: null,
    financing_program: null,
    car_source: null,
    knows_specific_car: null,
    occupation: null,
    customer_id_reference: null,
    tele_disposition: null,
    ds_disposition: null,
    tele_sla_due_at: null,
    tele_sla_breached: false,
    ds_sla_due_at: null,
    ds_sla_breached: false,
    tele_follow_up_at: null,
    ds_follow_up_at: null,
    id_document_url: null,
    tele_notes: null,
    ds_notes: null,
    unqualification_reason: null,
  },
]

export const MOCK_PROFILES: Profile[] = [
  MOCK_PROFILE,
  {
    id: 'ts-agent-002',
    full_name: 'Fatima Zahra',
    role: 'telesales_agent',
    team: 'telesales',
    is_active: true,
    is_on_break: true,
    break_started_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    shift_start: '09:00',
    shift_end: '18:00',
  },
  {
    id: 'ts-agent-003',
    full_name: 'Hassan Mahmoud',
    role: 'telesales_agent',
    team: 'telesales',
    is_active: true,
    is_on_break: false,
    break_started_at: null,
    shift_start: '09:00',
    shift_end: '18:00',
  },
  {
    id: 'ds-agent-001',
    full_name: 'Yasmine Nasser',
    role: 'direct_sales_agent',
    team: 'direct_sales',
    is_active: true,
    is_on_break: false,
    break_started_at: null,
    shift_start: '10:00',
    shift_end: '19:00',
  },
  {
    id: 'ds-agent-002',
    full_name: 'Tarek Adel',
    role: 'direct_sales_agent',
    team: 'direct_sales',
    is_active: true,
    is_on_break: false,
    break_started_at: null,
    shift_start: '10:00',
    shift_end: '19:00',
  },
]

export const MOCK_OCCUPATIONS: ConfigOccupation[] = [
  { id: 'occ-01', label: 'Engineer', sort_order: 1, is_active: true },
  { id: 'occ-02', label: 'Doctor', sort_order: 2, is_active: true },
  { id: 'occ-03', label: 'Lawyer', sort_order: 3, is_active: true },
  { id: 'occ-04', label: 'Accountant', sort_order: 4, is_active: true },
  { id: 'occ-05', label: 'Teacher', sort_order: 5, is_active: true },
  { id: 'occ-06', label: 'Business Owner', sort_order: 6, is_active: true },
  { id: 'occ-07', label: 'Government Employee', sort_order: 7, is_active: true },
  { id: 'occ-08', label: 'Military / Police', sort_order: 8, is_active: true },
  { id: 'occ-09', label: 'Pharmacist', sort_order: 9, is_active: true },
  { id: 'occ-10', label: 'Other', sort_order: 10, is_active: true },
]

export const MOCK_ATTENDANCE: DailyAttendance[] = [
  {
    id: 'att-001',
    agent_id: 'mock-user-id',
    date: new Date().toISOString().slice(0, 10),
    checked_in: true,
    checked_in_at: new Date(new Date().setHours(9, 3, 0, 0)).toISOString(),
    checked_out: false,
    checked_out_at: null,
    on_break: false,
    break_log: [],
  },
  {
    id: 'att-002',
    agent_id: 'ts-agent-002',
    date: new Date().toISOString().slice(0, 10),
    checked_in: true,
    checked_in_at: new Date(new Date().setHours(9, 10, 0, 0)).toISOString(),
    checked_out: false,
    checked_out_at: null,
    on_break: true,
    break_log: [
      {
        started_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        ended_at: null,
      },
    ],
  },
  {
    id: 'att-003',
    agent_id: 'ts-agent-003',
    date: new Date().toISOString().slice(0, 10),
    checked_in: true,
    checked_in_at: new Date(new Date().setHours(8, 58, 0, 0)).toISOString(),
    checked_out: false,
    checked_out_at: null,
    on_break: false,
    break_log: [
      {
        started_at: new Date(new Date().setHours(11, 0, 0, 0)).toISOString(),
        ended_at: new Date(new Date().setHours(11, 15, 0, 0)).toISOString(),
      },
    ],
  },
  {
    id: 'att-004',
    agent_id: 'ds-agent-001',
    date: new Date().toISOString().slice(0, 10),
    checked_in: true,
    checked_in_at: new Date(new Date().setHours(10, 5, 0, 0)).toISOString(),
    checked_out: false,
    checked_out_at: null,
    on_break: false,
    break_log: [],
  },
  {
    id: 'att-005',
    agent_id: 'ds-agent-002',
    date: new Date().toISOString().slice(0, 10),
    checked_in: false,
    checked_in_at: null,
    checked_out: false,
    checked_out_at: null,
    on_break: false,
    break_log: [],
  },
]
